CREATE TABLE CLIENT
(
    ID   INT PRIMARY KEY AUTO_INCREMENT,
    NAME text
);

CREATE TABLE ACCOUNT
(
    ID        INT PRIMARY KEY AUTO_INCREMENT,
    AMOUNT    decimal(10,2),
    NUMBER    text,
    CLIENT_ID int,
    FOREIGN KEY (CLIENT_ID)  REFERENCES CLIENT (ID)
);